# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\EricPython2\Query.ui'
#
# Created: Thu Apr 24 10:43:33 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(782, 338)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget_3 = QtGui.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("å¾®è½¯é›…é»‘"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setMouseTracking(True)
        self.tabWidget_3.setToolTip(_fromUtf8(""))
        self.tabWidget_3.setStatusTip(_fromUtf8(""))
        self.tabWidget_3.setStyleSheet(_fromUtf8("font: 9pt \"å¾®è½¯é›…é»‘\";"))
        self.tabWidget_3.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_3.setDocumentMode(False)
        self.tabWidget_3.setTabsClosable(False)
        self.tabWidget_3.setMovable(True)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.splitter_14 = QtGui.QSplitter(self.tab_5)
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_14)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_11 = QtGui.QLabel(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ddateTimeEdit1 = QtGui.QDateTimeEdit(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ddateTimeEdit1.sizePolicy().hasHeightForWidth())
        self.ddateTimeEdit1.setSizePolicy(sizePolicy)
        self.ddateTimeEdit1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ddateTimeEdit1.setAutoFillBackground(False)
        self.ddateTimeEdit1.setStyleSheet(_fromUtf8("background-color: rgb(113, 113, 113);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);"))
        self.ddateTimeEdit1.setDateTime(QtCore.QDateTime(QtCore.QDate(2012, 3, 31), QtCore.QTime(0, 0, 0)))
        self.ddateTimeEdit1.setCalendarPopup(True)
        self.ddateTimeEdit1.setObjectName(_fromUtf8("ddateTimeEdit1"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_14)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_12 = QtGui.QLabel(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ddateTimeEdit2 = QtGui.QDateTimeEdit(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ddateTimeEdit2.sizePolicy().hasHeightForWidth())
        self.ddateTimeEdit2.setSizePolicy(sizePolicy)
        self.ddateTimeEdit2.setStyleSheet(_fromUtf8("background-color: rgb(113, 113, 113);\n"
"font: 75 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);"))
        self.ddateTimeEdit2.setDateTime(QtCore.QDateTime(QtCore.QDate(2012, 5, 1), QtCore.QTime(0, 0, 0)))
        self.ddateTimeEdit2.setDate(QtCore.QDate(2012, 5, 1))
        self.ddateTimeEdit2.setCalendarPopup(True)
        self.ddateTimeEdit2.setTimeSpec(QtCore.Qt.OffsetFromUTC)
        self.ddateTimeEdit2.setObjectName(_fromUtf8("ddateTimeEdit2"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_14)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label_4 = QtGui.QLabel(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dcombox_place = QtGui.QComboBox(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcombox_place.sizePolicy().hasHeightForWidth())
        self.dcombox_place.setSizePolicy(sizePolicy)
        self.dcombox_place.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.dcombox_place.setObjectName(_fromUtf8("dcombox_place"))
        self.dcombox_place.addItem(_fromUtf8(""))
        self.dcombox_place.addItem(_fromUtf8(""))
        self.splitter_10 = QtGui.QSplitter(self.splitter_14)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_15 = QtGui.QLabel(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.dcombox_name = QtGui.QComboBox(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcombox_name.sizePolicy().hasHeightForWidth())
        self.dcombox_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DFKai-SB"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.dcombox_name.setFont(font)
        self.dcombox_name.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.dcombox_name.setMaxVisibleItems(12)
        self.dcombox_name.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.dcombox_name.setObjectName(_fromUtf8("dcombox_name"))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.dcombox_name.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.splitter_14, 2, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 2, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.line_1 = QtGui.QFrame(self.tab_5)
        self.line_1.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.line_1.setFrameShape(QtGui.QFrame.VLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout_9.addWidget(self.line_1, 0, 2, 3, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_5 = QtGui.QSplitter(self.tab_5)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_13 = QtGui.QLabel(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.dcombox_index = QtGui.QComboBox(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcombox_index.sizePolicy().hasHeightForWidth())
        self.dcombox_index.setSizePolicy(sizePolicy)
        self.dcombox_index.setStyleSheet(_fromUtf8("font: 75 12pt \"Calibri\";"))
        self.dcombox_index.setObjectName(_fromUtf8("dcombox_index"))
        self.label = QtGui.QLabel(self.splitter_5)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.splitter_5)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_6 = QtGui.QSplitter(self.tab_5)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.label_14 = QtGui.QLabel(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.dcombox_con = QtGui.QComboBox(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcombox_con.sizePolicy().hasHeightForWidth())
        self.dcombox_con.setSizePolicy(sizePolicy)
        self.dcombox_con.setStyleSheet(_fromUtf8("font: 75 12pt \"Calibri\";"))
        self.dcombox_con.setObjectName(_fromUtf8("dcombox_con"))
        self.dcombox_con.addItem(_fromUtf8(""))
        self.dcombox_con.addItem(_fromUtf8(""))
        self.dcombox_con.addItem(_fromUtf8(""))
        self.dcombox_con.addItem(_fromUtf8(""))
        self.dcombox_con.addItem(_fromUtf8(""))
        self.dlineEdit1 = QtGui.QLineEdit(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlineEdit1.sizePolicy().hasHeightForWidth())
        self.dlineEdit1.setSizePolicy(sizePolicy)
        self.dlineEdit1.setObjectName(_fromUtf8("dlineEdit1"))
        self.dlineEdit2 = QtGui.QLineEdit(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlineEdit2.sizePolicy().hasHeightForWidth())
        self.dlineEdit2.setSizePolicy(sizePolicy)
        self.dlineEdit2.setObjectName(_fromUtf8("dlineEdit2"))
        self.verticalLayout.addWidget(self.splitter_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.splitter_7 = QtGui.QSplitter(self.tab_5)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.layoutWidget = QtGui.QWidget(self.splitter_7)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dpb_add = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpb_add.sizePolicy().hasHeightForWidth())
        self.dpb_add.setSizePolicy(sizePolicy)
        self.dpb_add.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.dpb_add.setObjectName(_fromUtf8("dpb_add"))
        self.verticalLayout_2.addWidget(self.dpb_add)
        self.dpb_delete1 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpb_delete1.sizePolicy().hasHeightForWidth())
        self.dpb_delete1.setSizePolicy(sizePolicy)
        self.dpb_delete1.setBaseSize(QtCore.QSize(0, 0))
        self.dpb_delete1.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.dpb_delete1.setObjectName(_fromUtf8("dpb_delete1"))
        self.verticalLayout_2.addWidget(self.dpb_delete1)
        self.dpb_clear = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpb_clear.sizePolicy().hasHeightForWidth())
        self.dpb_clear.setSizePolicy(sizePolicy)
        self.dpb_clear.setBaseSize(QtCore.QSize(0, 0))
        self.dpb_clear.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.dpb_clear.setObjectName(_fromUtf8("dpb_clear"))
        self.verticalLayout_2.addWidget(self.dpb_clear)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.dlistWidget = QtGui.QListWidget(self.splitter_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlistWidget.sizePolicy().hasHeightForWidth())
        self.dlistWidget.setSizePolicy(sizePolicy)
        self.dlistWidget.setStyleSheet(_fromUtf8("background-color: rgb(205, 240, 211);"))
        self.dlistWidget.setProperty("isWrapping", False)
        self.dlistWidget.setLayoutMode(QtGui.QListView.SinglePass)
        self.dlistWidget.setSelectionRectVisible(False)
        self.dlistWidget.setObjectName(_fromUtf8("dlistWidget"))
        self.verticalLayout.addWidget(self.splitter_7)
        self.gridLayout_9.addLayout(self.verticalLayout, 0, 3, 3, 1)
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setStyleSheet(_fromUtf8("color: rgb(85, 85, 255);\n"
"font: 75 9pt \"Euclid Fraktur\";"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 2, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 2, 5, 1, 1)
        self.splitter = QtGui.QSplitter(self.tab_5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setStyleSheet(_fromUtf8("image: url(:/ProjectImages/zky.jpg);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_30 = QtGui.QLabel(self.splitter)
        self.label_30.setStyleSheet(_fromUtf8("font: 75 10pt \"é»‘ä½“\";"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_9.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_11 = QtGui.QSplitter(self.tab_3)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName(_fromUtf8("splitter_11"))
        self.gridLayout_4.addWidget(self.splitter_11, 0, 0, 1, 1)
        self.splitter_12 = QtGui.QSplitter(self.tab_3)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_12)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_4.addWidget(self.splitter_12, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.tab_3)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_4.addWidget(self.line_8, 3, 0, 1, 2)
        self.tabWidget_3.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.splitter_13 = QtGui.QSplitter(self.tab_4)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.label_17 = QtGui.QLabel(self.splitter_13)
        self.label_17.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.t5spinBox1 = QtGui.QSpinBox(self.splitter_13)
        self.t5spinBox1.setProperty("value", 2)
        self.t5spinBox1.setObjectName(_fromUtf8("t5spinBox1"))
        self.label_10 = QtGui.QLabel(self.splitter_13)
        self.label_10.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_15.addWidget(self.splitter_13)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.t5pushButton_okall = QtGui.QPushButton(self.tab_4)
        self.t5pushButton_okall.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.t5pushButton_okall.setObjectName(_fromUtf8("t5pushButton_okall"))
        self.horizontalLayout_8.addWidget(self.t5pushButton_okall)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.t5pushButton_cancel = QtGui.QPushButton(self.tab_4)
        self.t5pushButton_cancel.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.t5pushButton_cancel.setObjectName(_fromUtf8("t5pushButton_cancel"))
        self.horizontalLayout_9.addWidget(self.t5pushButton_cancel)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem10)
        self.horizontalLayout_10.addLayout(self.verticalLayout_15)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_11.addWidget(self.label_20)
        self.checkBox_PAA = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_PAA.sizePolicy().hasHeightForWidth())
        self.checkBox_PAA.setSizePolicy(sizePolicy)
        self.checkBox_PAA.setObjectName(_fromUtf8("checkBox_PAA"))
        self.verticalLayout_11.addWidget(self.checkBox_PAA)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_11.addWidget(self.label_7)
        self.checkBox_PLREFP = QtGui.QCheckBox(self.tab_4)
        self.checkBox_PLREFP.setObjectName(_fromUtf8("checkBox_PLREFP"))
        self.verticalLayout_11.addWidget(self.checkBox_PLREFP)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.checkBox_SW = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_SW.sizePolicy().hasHeightForWidth())
        self.checkBox_SW.setSizePolicy(sizePolicy)
        self.checkBox_SW.setObjectName(_fromUtf8("checkBox_SW"))
        self.verticalLayout_11.addWidget(self.checkBox_SW)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_11.addWidget(self.label_9)
        self.checkBox_BU = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_BU.sizePolicy().hasHeightForWidth())
        self.checkBox_BU.setSizePolicy(sizePolicy)
        self.checkBox_BU.setObjectName(_fromUtf8("checkBox_BU"))
        self.verticalLayout_11.addWidget(self.checkBox_BU)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_12.addWidget(self.label_18)
        self.t5spinBoxPAA1 = QtGui.QSpinBox(self.tab_4)
        self.t5spinBoxPAA1.setMaximum(99999)
        self.t5spinBoxPAA1.setProperty("value", 5)
        self.t5spinBoxPAA1.setObjectName(_fromUtf8("t5spinBoxPAA1"))
        self.verticalLayout_12.addWidget(self.t5spinBoxPAA1)
        self.line_9 = QtGui.QFrame(self.tab_4)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_12.addWidget(self.line_9)
        self.line_11 = QtGui.QFrame(self.tab_4)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_12.addWidget(self.line_11)
        self.t5spinBoxPLREFP1 = QtGui.QSpinBox(self.tab_4)
        self.t5spinBoxPLREFP1.setMaximum(99999)
        self.t5spinBoxPLREFP1.setProperty("value", 3)
        self.t5spinBoxPLREFP1.setObjectName(_fromUtf8("t5spinBoxPLREFP1"))
        self.verticalLayout_12.addWidget(self.t5spinBoxPLREFP1)
        self.line_13 = QtGui.QFrame(self.tab_4)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_12.addWidget(self.line_13)
        self.line_12 = QtGui.QFrame(self.tab_4)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_12.addWidget(self.line_12)
        self.t5doubleSpinBoxSW1 = QtGui.QDoubleSpinBox(self.tab_4)
        self.t5doubleSpinBoxSW1.setSingleStep(0.01)
        self.t5doubleSpinBoxSW1.setProperty("value", 0.1)
        self.t5doubleSpinBoxSW1.setObjectName(_fromUtf8("t5doubleSpinBoxSW1"))
        self.verticalLayout_12.addWidget(self.t5doubleSpinBoxSW1)
        self.line_15 = QtGui.QFrame(self.tab_4)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout_12.addWidget(self.line_15)
        self.line_14 = QtGui.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout_12.addWidget(self.line_14)
        self.t5doubleSpinBoxBU1 = QtGui.QDoubleSpinBox(self.tab_4)
        self.t5doubleSpinBoxBU1.setSingleStep(0.01)
        self.t5doubleSpinBoxBU1.setObjectName(_fromUtf8("t5doubleSpinBoxBU1"))
        self.verticalLayout_12.addWidget(self.t5doubleSpinBoxBU1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_13.addWidget(self.label_25)
        self.t5lineEdit_PAA2 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_PAA2.setEnabled(True)
        self.t5lineEdit_PAA2.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_PAA2.setFrame(True)
        self.t5lineEdit_PAA2.setEchoMode(QtGui.QLineEdit.Normal)
        self.t5lineEdit_PAA2.setDragEnabled(False)
        self.t5lineEdit_PAA2.setReadOnly(True)
        self.t5lineEdit_PAA2.setObjectName(_fromUtf8("t5lineEdit_PAA2"))
        self.verticalLayout_13.addWidget(self.t5lineEdit_PAA2)
        self.line_16 = QtGui.QFrame(self.tab_4)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout_13.addWidget(self.line_16)
        self.line_17 = QtGui.QFrame(self.tab_4)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout_13.addWidget(self.line_17)
        self.t5lineEdit_PLREFP2 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_PLREFP2.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_PLREFP2.setReadOnly(True)
        self.t5lineEdit_PLREFP2.setObjectName(_fromUtf8("t5lineEdit_PLREFP2"))
        self.verticalLayout_13.addWidget(self.t5lineEdit_PLREFP2)
        self.line_18 = QtGui.QFrame(self.tab_4)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.verticalLayout_13.addWidget(self.line_18)
        self.line_19 = QtGui.QFrame(self.tab_4)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.verticalLayout_13.addWidget(self.line_19)
        self.t5lineEdit_SW2 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_SW2.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_SW2.setDragEnabled(False)
        self.t5lineEdit_SW2.setReadOnly(True)
        self.t5lineEdit_SW2.setObjectName(_fromUtf8("t5lineEdit_SW2"))
        self.verticalLayout_13.addWidget(self.t5lineEdit_SW2)
        self.line_20 = QtGui.QFrame(self.tab_4)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.verticalLayout_13.addWidget(self.line_20)
        self.line_21 = QtGui.QFrame(self.tab_4)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.verticalLayout_13.addWidget(self.line_21)
        self.t5lineEdit_BU2 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_BU2.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_BU2.setReadOnly(True)
        self.t5lineEdit_BU2.setObjectName(_fromUtf8("t5lineEdit_BU2"))
        self.verticalLayout_13.addWidget(self.t5lineEdit_BU2)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem13)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setStyleSheet(_fromUtf8("font: 75 10pt \"DFKai-SB\";"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_14.addWidget(self.label_21)
        self.t5lineEdit_PAA3 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_PAA3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_PAA3.setDragEnabled(False)
        self.t5lineEdit_PAA3.setReadOnly(True)
        self.t5lineEdit_PAA3.setObjectName(_fromUtf8("t5lineEdit_PAA3"))
        self.verticalLayout_14.addWidget(self.t5lineEdit_PAA3)
        self.line_23 = QtGui.QFrame(self.tab_4)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.verticalLayout_14.addWidget(self.line_23)
        self.line_22 = QtGui.QFrame(self.tab_4)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.verticalLayout_14.addWidget(self.line_22)
        self.t5lineEdit_PLREFP3 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_PLREFP3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_PLREFP3.setReadOnly(True)
        self.t5lineEdit_PLREFP3.setObjectName(_fromUtf8("t5lineEdit_PLREFP3"))
        self.verticalLayout_14.addWidget(self.t5lineEdit_PLREFP3)
        self.line_24 = QtGui.QFrame(self.tab_4)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.verticalLayout_14.addWidget(self.line_24)
        self.line_25 = QtGui.QFrame(self.tab_4)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.verticalLayout_14.addWidget(self.line_25)
        self.t5lineEdit_SW3 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_SW3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_SW3.setReadOnly(True)
        self.t5lineEdit_SW3.setObjectName(_fromUtf8("t5lineEdit_SW3"))
        self.verticalLayout_14.addWidget(self.t5lineEdit_SW3)
        self.line_27 = QtGui.QFrame(self.tab_4)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.verticalLayout_14.addWidget(self.line_27)
        self.line_26 = QtGui.QFrame(self.tab_4)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.verticalLayout_14.addWidget(self.line_26)
        self.t5lineEdit_BU3 = QtGui.QLineEdit(self.tab_4)
        self.t5lineEdit_BU3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);"))
        self.t5lineEdit_BU3.setReadOnly(True)
        self.t5lineEdit_BU3.setObjectName(_fromUtf8("t5lineEdit_BU3"))
        self.verticalLayout_14.addWidget(self.t5lineEdit_BU3)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.tabWidget_3.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget_3.setCurrentIndex(0)
        self.dcombox_name.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_11.setText(_translate("Dialog", "èµ·å§‹", None))
        self.label_12.setText(_translate("Dialog", "ç»ˆæ­¢", None))
        self.label_4.setText(_translate("Dialog", "åœ°ç‚¹", None))
        self.dcombox_place.setItemText(0, _translate("Dialog", "åŒ—äº¬", None))
        self.dcombox_place.setItemText(1, _translate("Dialog", "å�ˆè‚¥", None))
        self.label_15.setText(_translate("Dialog", "ä»ªå™¨", None))
        self.dcombox_name.setItemText(0, _translate("Dialog", "é€‰æ‹©ä»ªå™¨", None))
        self.dcombox_name.setItemText(1, _translate("Dialog", "è¿‘åœ°é�¢æµ‹é‡�ç³»ç»Ÿ", None))
        self.dcombox_name.setItemText(2, _translate("Dialog", "æ¹�æµ�æŽ¢æµ‹æ¿€å…‰é›·è¾¾", None))
        self.dcombox_name.setItemText(3, _translate("Dialog", "Airda16000ä½Žå¹³æµ�å±‚é£Žå»“çº¿é›·è¾¾", None))
        self.dcombox_name.setItemText(4, _translate("Dialog", "å…¨å¤©ç©ºæˆ�åƒ�ä»ª", None))
        self.dcombox_name.setItemText(5, _translate("Dialog", "å¤§å­”å¾„é—ªçƒ�ä»ª", None))
        self.dcombox_name.setItemText(6, _translate("Dialog", "POM-02å¤ªé˜³è¾�å°„è®¡", None))
        self.dcombox_name.setItemText(7, _translate("Dialog", "DTFå¤ªé˜³è¾�å°„è®¡", None))
        self.dcombox_name.setItemText(8, _translate("Dialog", "PGSå¤ªé˜³è¾�å°„è®¡", None))
        self.dcombox_name.setItemText(9, _translate("Dialog", "æ¸©åº¦è„‰åŠ¨ä»ª", None))
        self.dcombox_name.setItemText(10, _translate("Dialog", "è‡ªåŠ¨æ°”è±¡ç«™ï¼ŒCO2ä¼ æ„Ÿå™¨", None))
        self.dcombox_name.setItemText(11, _translate("Dialog", "å¸¸è§„æ°”è±¡å�‚æ•°æµ‹é‡�ç³»ç»Ÿ", None))
        self.dcombox_name.setItemText(12, _translate("Dialog", "å›¾åƒ�é‡‡é›†ç³»ç»Ÿ", None))
        self.dcombox_name.setItemText(13, _translate("Dialog", "å…‰çº¤æ¹�æµ�æµ‹é‡�ç³»ç»Ÿ", None))
        self.dcombox_name.setItemText(14, _translate("Dialog", "å¤§æ°”èƒ½è§�åº¦ä»ª", None))
        self.dcombox_name.setItemText(15, _translate("Dialog", "å…‰å­¦ç²’å­�è®¡æ•°å™¨", None))
        self.dcombox_name.setItemText(16, _translate("Dialog", "å¾®è„‰å†²æ¿€å…‰é›·è¾¾", None))
        self.dcombox_name.setItemText(17, _translate("Dialog", "å…‰çº¤å…‰è°±ä»ª", None))
        self.dcombox_name.setItemText(18, _translate("Dialog", "APS3321", None))
        self.dcombox_name.setItemText(19, _translate("Dialog", "ç‚­é»‘ä»ªï¼ŒæµŠåº¦è®¡", None))
        self.dcombox_name.setItemText(20, _translate("Dialog", "æ‰‹æŒ�å¤ªé˜³è¾�å°„è®¡", None))
        self.dcombox_name.setItemText(21, _translate("Dialog", "è½¦è½½é£Žé›·è¾¾", None))
        self.dcombox_name.setItemText(22, _translate("Dialog", "å¤§æ°”ç›¸å¹²é•¿åº¦ä»ª", None))
        self.dcombox_name.setItemText(23, _translate("Dialog", "å¤©ç©ºäº®åº¦ä»ª", None))
        self.label_13.setText(_translate("Dialog", "å­—æ®µ", None))
        self.label_14.setText(_translate("Dialog", "æ�¡ä»¶", None))
        self.dcombox_con.setItemText(0, _translate("Dialog", ">...", None))
        self.dcombox_con.setItemText(1, _translate("Dialog", "<...", None))
        self.dcombox_con.setItemText(2, _translate("Dialog", "=...", None))
        self.dcombox_con.setItemText(3, _translate("Dialog", "between...and...", None))
        self.dcombox_con.setItemText(4, _translate("Dialog", "is", None))
        self.dpb_add.setText(_translate("Dialog", "æ·»åŠ ", None))
        self.dpb_delete1.setText(_translate("Dialog", "åˆ é™¤", None))
        self.dpb_clear.setText(_translate("Dialog", "æ¸…ç©º", None))
        self.label_26.setText(_translate("Dialog", "This A Python&Qt Work!Welcome To Database System!", None))
        self.label_30.setText(_translate("Dialog", "  å¤§æ°”å…‰å­¦ç‰¹æ€§ç ”ç©¶å®¤", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("Dialog", "å�•è¡¨æŸ¥è¯¢", None))
        self.tabWidget_3.setTabToolTip(self.tabWidget_3.indexOf(self.tab_5), _translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">æŸ¥è¯¢æŽ§åˆ¶å�°</p></body></html>", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("Dialog", "å¤šè¡¨æŸ¥è¯¢", None))
        self.tabWidget_3.setTabToolTip(self.tabWidget_3.indexOf(self.tab_3), _translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">æ•°æ�®å¤„ç�†</p></body></html>", None))
        self.label_17.setText(_translate("Dialog", "ç¬¬", None))
        self.label_10.setText(_translate("Dialog", "åˆ—", None))
        self.t5pushButton_okall.setText(_translate("Dialog", "å…¨é€‰", None))
        self.t5pushButton_cancel.setText(_translate("Dialog", "å�–æ¶ˆ", None))
        self.label_20.setText(_translate("Dialog", "åˆ†æ®µç®—æ³•", None))
        self.checkBox_PAA.setText(_translate("Dialog", "PAA", None))
        self.checkBox_PLREFP.setText(_translate("Dialog", "PLR_EFP", None))
        self.checkBox_SW.setText(_translate("Dialog", "SW", None))
        self.checkBox_BU.setText(_translate("Dialog", "BU", None))
        self.label_18.setText(_translate("Dialog", "é˜ˆå€¼å�‚æ•°", None))
        self.label_25.setText(_translate("Dialog", "åŽ‹ç¼©åº¦", None))
        self.label_21.setText(_translate("Dialog", "æ‹Ÿå�ˆè¯¯å·®", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("Dialog", "æ•°æ�®åŽ‹ç¼©", None))
        self.tabWidget_3.setTabToolTip(self.tabWidget_3.indexOf(self.tab_4), _translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">æ•°æ�®åˆ†æž�</p></body></html>", None))

import Image_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

