# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\EricPython5\AOPAS\setting.ui'
#
# Created: Mon Jun 09 11:44:10 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName(_fromUtf8("Setting"))
        Setting.setWindowModality(QtCore.Qt.WindowModal)
        Setting.resize(364, 550)
        Setting.setMaximumSize(QtCore.QSize(3700, 3300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ProjectImages/options_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Setting.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Setting)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_2 = QtGui.QSplitter(Setting)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.settinglineEdit0 = QtGui.QLineEdit(self.widget)
        self.settinglineEdit0.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.settinglineEdit0.setObjectName(_fromUtf8("settinglineEdit0"))
        self.horizontalLayout_5.addWidget(self.settinglineEdit0)
        self.widget1 = QtGui.QWidget(self.splitter_2)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.widget1)
        self.label.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.settinglineEdit1 = QtGui.QLineEdit(self.widget1)
        self.settinglineEdit1.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.settinglineEdit1.setObjectName(_fromUtf8("settinglineEdit1"))
        self.horizontalLayout_3.addWidget(self.settinglineEdit1)
        self.line_4 = QtGui.QFrame(self.splitter_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 3)
        self.splitter_3 = QtGui.QSplitter(Setting)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget2 = QtGui.QWidget(self.splitter_3)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.widget2)
        self.comboBox.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.textEdit = QtGui.QTextEdit(self.splitter)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.widget3 = QtGui.QWidget(self.splitter)
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.gridLayout = QtGui.QGridLayout(self.widget3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.widget3)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.settinglineEdit2 = QtGui.QLineEdit(self.widget3)
        self.settinglineEdit2.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.settinglineEdit2.setObjectName(_fromUtf8("settinglineEdit2"))
        self.gridLayout.addWidget(self.settinglineEdit2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget3)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.settinglineEdit3 = QtGui.QLineEdit(self.widget3)
        self.settinglineEdit3.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.settinglineEdit3.setObjectName(_fromUtf8("settinglineEdit3"))
        self.gridLayout.addWidget(self.settinglineEdit3, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget3)
        self.label_5.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.settinglineEdit4 = QtGui.QLineEdit(self.widget3)
        self.settinglineEdit4.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.settinglineEdit4.setEchoMode(QtGui.QLineEdit.Password)
        self.settinglineEdit4.setObjectName(_fromUtf8("settinglineEdit4"))
        self.gridLayout.addWidget(self.settinglineEdit4, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.splitter)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_3 = QtGui.QFrame(self.splitter)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.splitter_3, 1, 0, 1, 3)
        self.splitter_4 = QtGui.QSplitter(Setting)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.line_5 = QtGui.QFrame(self.splitter_4)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.splitter_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.widget4 = QtGui.QWidget(self.splitter_4)
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.widget4)
        self.pushButton.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtGui.QPushButton(self.widget4)
        self.pushButton_2.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_2.addWidget(self.splitter_4, 5, 0, 1, 3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_3 = QtGui.QPushButton(Setting)
        self.pushButton_3.setStyleSheet(_fromUtf8("font: 75 12pt \"DFKai-SB\";"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.textEdit_2 = QtGui.QTextEdit(Setting)
        self.textEdit_2.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.horizontalLayout_4.addWidget(self.textEdit_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 0, 1, 1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        Setting.setWindowTitle(_translate("Setting", "系统设置", None))
        self.label_6.setText(_translate("Setting", "数据库IP  ", None))
        self.label.setText(_translate("Setting", "数据库实例", None))
        self.label_2.setText(_translate("Setting", "数据库驱动", None))
        self.comboBox.setItemText(0, _translate("Setting", "Default", None))
        self.comboBox.setItemText(1, _translate("Setting", "MS SQLSERVER", None))
        self.comboBox.setItemText(2, _translate("Setting", "MYSQL", None))
        self.comboBox.setItemText(3, _translate("Setting", "POSTSQL", None))
        self.comboBox.setItemText(4, _translate("Setting", "ORCALE", None))
        self.label_3.setText(_translate("Setting", "数据库名", None))
        self.label_4.setText(_translate("Setting", "用户名", None))
        self.label_5.setText(_translate("Setting", "密码", None))
        self.pushButton.setText(_translate("Setting", "确定", None))
        self.pushButton_2.setText(_translate("Setting", "重置", None))
        self.pushButton_3.setText(_translate("Setting", "测试连接", None))

import Image_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Setting = QtGui.QDialog()
    ui = Ui_Setting()
    ui.setupUi(Setting)
    Setting.show()
    sys.exit(app.exec_())

