# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\EricPython5\AOPAS\StartDialog.ui'
#
# Created: Mon Jun 09 11:44:12 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StartDialog(object):
    def setupUi(self, StartDialog):
        StartDialog.setObjectName(_fromUtf8("StartDialog"))
        StartDialog.resize(453, 418)
        self.gridLayout_2 = QtGui.QGridLayout(StartDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QTextEdit(StartDialog)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.splitter_11 = QtGui.QSplitter(StartDialog)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName(_fromUtf8("splitter_11"))
        self.label_10 = QtGui.QLabel(self.splitter_11)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEditUser = QtGui.QLineEdit(self.splitter_11)
        self.lineEditUser.setText(_fromUtf8(""))
        self.lineEditUser.setReadOnly(True)
        self.lineEditUser.setObjectName(_fromUtf8("lineEditUser"))
        self.verticalLayout.addWidget(self.splitter_11)
        self.splitter_10 = QtGui.QSplitter(StartDialog)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_11 = QtGui.QLabel(self.splitter_10)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEditLimits = QtGui.QLineEdit(self.splitter_10)
        self.lineEditLimits.setReadOnly(True)
        self.lineEditLimits.setObjectName(_fromUtf8("lineEditLimits"))
        self.verticalLayout.addWidget(self.splitter_10)
        self.splitter_12 = QtGui.QSplitter(StartDialog)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.pbOK = QtGui.QPushButton(self.splitter_12)
        self.pbOK.setObjectName(_fromUtf8("pbOK"))
        self.pbQuit = QtGui.QPushButton(self.splitter_12)
        self.pbQuit.setObjectName(_fromUtf8("pbQuit"))
        self.verticalLayout.addWidget(self.splitter_12)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(StartDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pBUserManage = QtGui.QPushButton(self.splitter)
        self.pBUserManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/user.png);"))
        self.pBUserManage.setText(_fromUtf8(""))
        self.pBUserManage.setObjectName(_fromUtf8("pBUserManage"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.line_5 = QtGui.QFrame(StartDialog)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 0, 1, 1, 1)
        self.splitter_2 = QtGui.QSplitter(StartDialog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pBProjectManage = QtGui.QPushButton(self.splitter_2)
        self.pBProjectManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/open.png);"))
        self.pBProjectManage.setText(_fromUtf8(""))
        self.pBProjectManage.setObjectName(_fromUtf8("pBProjectManage"))
        self.label_2 = QtGui.QLabel(self.splitter_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.splitter_2, 0, 2, 1, 2)
        self.line_4 = QtGui.QFrame(StartDialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 0, 4, 1, 1)
        self.splitter_3 = QtGui.QSplitter(StartDialog)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pBLogManage = QtGui.QPushButton(self.splitter_3)
        self.pBLogManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/calendar.png);"))
        self.pBLogManage.setText(_fromUtf8(""))
        self.pBLogManage.setObjectName(_fromUtf8("pBLogManage"))
        self.label_3 = QtGui.QLabel(self.splitter_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.splitter_3, 0, 5, 1, 2)
        self.line = QtGui.QFrame(StartDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 7)
        self.splitter_4 = QtGui.QSplitter(StartDialog)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.pBPlaceManage = QtGui.QPushButton(self.splitter_4)
        self.pBPlaceManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/search.png);"))
        self.pBPlaceManage.setText(_fromUtf8(""))
        self.pBPlaceManage.setObjectName(_fromUtf8("pBPlaceManage"))
        self.label_4 = QtGui.QLabel(self.splitter_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.splitter_4, 2, 0, 1, 1)
        self.line_3 = QtGui.QFrame(StartDialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 2, 1, 1, 1)
        self.splitter_5 = QtGui.QSplitter(StartDialog)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.pBInstruManage = QtGui.QPushButton(self.splitter_5)
        self.pBInstruManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/201211.ico);"))
        self.pBInstruManage.setText(_fromUtf8(""))
        self.pBInstruManage.setObjectName(_fromUtf8("pBInstruManage"))
        self.label_5 = QtGui.QLabel(self.splitter_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.splitter_5, 2, 2, 1, 2)
        self.line_6 = QtGui.QFrame(StartDialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 2, 4, 1, 1)
        self.splitter_6 = QtGui.QSplitter(StartDialog)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.pBPersonnelManage = QtGui.QPushButton(self.splitter_6)
        self.pBPersonnelManage.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/PLR.png);"))
        self.pBPersonnelManage.setText(_fromUtf8(""))
        self.pBPersonnelManage.setObjectName(_fromUtf8("pBPersonnelManage"))
        self.label_6 = QtGui.QLabel(self.splitter_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.splitter_6, 2, 5, 1, 2)
        self.line_2 = QtGui.QFrame(StartDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 7)
        self.splitter_7 = QtGui.QSplitter(StartDialog)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.pBExperiment = QtGui.QPushButton(self.splitter_7)
        self.pBExperiment.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/lamp_active.png);"))
        self.pBExperiment.setText(_fromUtf8(""))
        self.pBExperiment.setObjectName(_fromUtf8("pBExperiment"))
        self.label_8 = QtGui.QLabel(self.splitter_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.splitter_7, 4, 0, 1, 1)
        self.line_7 = QtGui.QFrame(StartDialog)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout.addWidget(self.line_7, 4, 1, 1, 2)
        self.splitter_8 = QtGui.QSplitter(StartDialog)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.pbDataImport = QtGui.QPushButton(self.splitter_8)
        self.pbDataImport.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/arrow_left.png);"))
        self.pbDataImport.setText(_fromUtf8(""))
        self.pbDataImport.setObjectName(_fromUtf8("pbDataImport"))
        self.label_7 = QtGui.QLabel(self.splitter_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.splitter_8, 4, 3, 1, 1)
        self.line_8 = QtGui.QFrame(StartDialog)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout.addWidget(self.line_8, 4, 4, 1, 2)
        self.splitter_9 = QtGui.QSplitter(StartDialog)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.pbMainWindow = QtGui.QPushButton(self.splitter_9)
        self.pbMainWindow.setStyleSheet(_fromUtf8("border-image: url(:/ProjectImages/refresh.png);"))
        self.pbMainWindow.setText(_fromUtf8(""))
        self.pbMainWindow.setObjectName(_fromUtf8("pbMainWindow"))
        self.label_9 = QtGui.QLabel(self.splitter_9)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.splitter_9, 4, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(StartDialog)
        QtCore.QMetaObject.connectSlotsByName(StartDialog)

    def retranslateUi(self, StartDialog):
        StartDialog.setWindowTitle(_translate("StartDialog", "导航控制台", None))
        self.textEdit.setHtml(_translate("StartDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   导航控制台介绍</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">导航控制台主要提供给系统管理员使用，若点击图标按钮无反应，请确定已登录并具有管理员权限。</p></body></html>", None))
        self.label_10.setText(_translate("StartDialog", "当前用户", None))
        self.label_11.setText(_translate("StartDialog", "用户状态", None))
        self.pbOK.setText(_translate("StartDialog", "确定", None))
        self.pbQuit.setText(_translate("StartDialog", "退出", None))
        self.label.setText(_translate("StartDialog", "用户管理", None))
        self.label_2.setText(_translate("StartDialog", "项目管理", None))
        self.label_3.setText(_translate("StartDialog", "日志管理", None))
        self.label_4.setText(_translate("StartDialog", "地点管理", None))
        self.label_5.setText(_translate("StartDialog", "仪器管理", None))
        self.label_6.setText(_translate("StartDialog", "人员管理", None))
        self.label_8.setText(_translate("StartDialog", "实验信息", None))
        self.label_7.setText(_translate("StartDialog", "数据导入", None))
        self.label_9.setText(_translate("StartDialog", "数据平台", None))

import Image_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    StartDialog = QtGui.QDialog()
    ui = Ui_StartDialog()
    ui.setupUi(StartDialog)
    StartDialog.show()
    sys.exit(app.exec_())

